"""add playlists table

Revision ID: f272564fffc1
Revises: 
Create Date: 2026-06-18 23:08:26.655220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f272564fffc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('youtube_playlist_id', sa.String(length=100), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('total_videos', sa.Integer(), nullable=False),
    sa.Column('video_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_playlists_youtube_playlist_id'), 'playlists', ['youtube_playlist_id'], unique=False)
    op.add_column('videos', sa.Column('playlist_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_videos_playlist_id'), 'videos', ['playlist_id'], unique=False)
    op.create_foreign_key(None, 'videos', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_index(op.f('ix_videos_playlist_id'), table_name='videos')
    op.drop_column('videos', 'playlist_id')
    op.drop_index(op.f('ix_playlists_youtube_playlist_id'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_table('playlists')
    # ### end Alembic commands ###
